services:
  db:
    image: postgres:17-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - db_data:/var/lib/postgresql/data

  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    entrypoint: ["bin/docker-entrypoint"]
    command: bash -c "rm -f tmp/pids/server.pid && ./bin/rails server -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    environment:
      RAILS_LOG_TO_STDOUT: "true"
    depends_on:
      - db

  worker:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: ["bin/jobs"]
    volumes:
      - .:/app
    environment:
      RAILS_LOG_TO_STDOUT: "true"
    depends_on:
      - db

volumes:
  db_data:
